#include <stdio.h>
#include <list_debug.h>
#include <list_func.h>

/* TODO: Check that it works before comit :)

    First attempt to launch executable generated by Makefile:

sh: 1: cannot create graph_dumps/dump_0.jpeg: Directory nonexistent
sh: 1: cannot create graph_dumps/dump_1.jpeg: Directory nonexistent
AddressSanitizer:DEADLYSIGNAL
=================================================================
==6101==ERROR: AddressSanitizer: SEGV on unknown address 0x610cf0f0f130 (pc 0x56252402d985 bp 0x7ffc036cb1a0 sp 0x7ffc036cb1a0 T0)
==6101==The signal is caused by a READ memory access.
    #0 0x56252402d984 in list_swap_prev(List*, unsigned long, unsigned long) (/home/matmuh/Desktop/code_review/Demoren1_List/list+0x1984)
    #1 0x56252402d895 in list_add(List*, unsigned long, int) (/home/matmuh/Desktop/code_review/Demoren1_List/list+0x1895)
    #2 0x56252402d467 in main (/home/matmuh/Desktop/code_review/Demoren1_List/list+0x1467)
    #3 0x7f1d8ff8a082 in __libc_start_main ../csu/libc-start.c:308
    #4 0x56252402d20d in _start (/home/matmuh/Desktop/code_review/Demoren1_List/list+0x120d)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/home/matmuh/Desktop/code_review/Demoren1_List/list+0x1984) in list_swap_prev(List*, unsigned long, unsigned long)
==6101==ABORTING

    Then I created this folder and got it:

AddressSanitizer:DEADLYSIGNAL
=================================================================
==6111==ERROR: AddressSanitizer: SEGV on unknown address 0x610cf0f0f130 (pc 0x55a8a0cd3985 bp 0x7ffd6faaed90 sp 0x7ffd6faaed90 T0)
==6111==The signal is caused by a READ memory access.
    #0 0x55a8a0cd3984 in list_swap_prev(List*, unsigned long, unsigned long) (/home/matmuh/Desktop/code_review/Demoren1_List/list+0x1984)
    #1 0x55a8a0cd3895 in list_add(List*, unsigned long, int) (/home/matmuh/Desktop/code_review/Demoren1_List/list+0x1895)
    #2 0x55a8a0cd3467 in main (/home/matmuh/Desktop/code_review/Demoren1_List/list+0x1467)
    #3 0x7f88ebcce082 in __libc_start_main ../csu/libc-start.c:308
    #4 0x55a8a0cd320d in _start (/home/matmuh/Desktop/code_review/Demoren1_List/list+0x120d)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/home/matmuh/Desktop/code_review/Demoren1_List/list+0x1984) in list_swap_prev(List*, unsigned long, unsigned long)
==6111==ABORTING

*/

int main()
{
    LIST_CHECK_FUNC(open_list_logs());

    List_t list = {};
    LIST_CTOR(list, 10);
    
    // printf("in main free head = %d, free tail = %d\n", list.free_head, list.free_tail);
    
    DUMP_LIST(&list);

    for (int i = 1; i < 6; i ++)
    {
        PUSH_IN_LIST(&list, i*10);
    }
    
    list_add(&list, 3, 25);
    list_add(&list, 3, 25);
    list_add(&list, 3, 25);

    DUMP_LIST(&list); 


    list_add(&list, 3, 25);
    list_add(&list, 3, 25);
    list_add(&list, 3, 25);
    list_add(&list, 3, 25);



    // DUMP_LIST(&list); 

    // POP_FROM_LIST(&list);

    // list_del(&list, 7);

    // DUMP_LIST(&list); 

    // list_sort(&list);

    // DUMP_LIST(&list); 

    int tmp = list_find(&list, 4);
    printf("tmp = %d\n", tmp);
    DUMP_LIST(&list);

    // list_add(&list, 1, 1488);
    // DUMP_LIST(&list);
    // list_del(&list, 3);
    // list_del(&list, 7);
    // DUMP_LIST(&list);  

    list_detor(&list);
    LIST_CHECK_FUNC(close_list_logs());
    return 0;
}